name: Build APK

on:
  push:
    branches:
      - master  # 或其他希望触发构建的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Java 8 环境
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      # 配置 JAVA_HOME 环境变量
      - name: Set JAVA_HOME to Java 8
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/zulu-8-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # 使用较旧的 Flutter 版本以支持 Android V1 嵌入
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'  # 使用适合的 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      # 强制使用 V1 嵌入并跳过过时警告
      - name: Build APK
        run: flutter build apk --release --no-sound-null-safety --ignore-deprecation

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
