name: Build APK

on:
  push:
    branches:
      - master  # 或其他希望触发构建的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Java 8 环境
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      # 动态获取 Java 8 的路径
      - name: Find Java 8 Path
        run: |
          JAVA_PATH=$(update-alternatives --list java | grep java-8 | head -n 1)
          if [ -z "$JAVA_PATH" ]; then
            echo "Java 8 not found!" && exit 1
          fi
          echo "JAVA_HOME=$(dirname $(dirname $JAVA_PATH))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # 使用较旧的 Flutter 版本以支持 Android V1 嵌入
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'  # 使用适合的 Flutter 版本

      # 检查 Flutter 环境
      - name: Doctor check
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      # 强制使用 V1 嵌入并跳过过时警告
      - name: Build APK
        run: flutter build apk --release --no-sound-null-safety --ignore-deprecation

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
