name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java 8
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk

      - name: Set JAVA_HOME to Java 8
        run: |
          JAVA_PATH=$(update-alternatives --list java | grep java-8 | head -n 1)
          if [ -z "$JAVA_PATH" ]; then
            echo "Java 8 not found!"
            exit 1
          fi
          echo "JAVA_HOME=$(dirname $(dirname $JAVA_PATH))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          export JAVA_HOME=$(dirname $(dirname $JAVA_PATH))
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          export JAVA_HOME=$JAVA_HOME
          export PATH=$JAVA_HOME/bin:$PATH
          flutter build apk --release --no-sound-null-safety --ignore-deprecation

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
